from typing import Any, Optional, Union, List, Dict, TypeVar, Generic, Callable
from pathlib import Path
import pandas as pd

T = TypeVar('T')

class DataFrame:
    columns: List[str]
    
    def select(self, *cols: str) -> 'DataFrame': ...
    def count(self) -> int: ...
    def write(self) -> DataFrameWriter: ...
    def collect(self) -> List[Row]: ...

class DataFrameWriter:
    def parquet(self, path: Union[str, Path], mode: str = ...) -> None: ...
    def save(self, path: Optional[str] = ..., format: Optional[str] = ..., mode: str = ..., **options: Any) -> None: ...

class SparkSession:
    builder: 'SparkSession.Builder'
    
    def createDataFrame(self, data: Union[pd.DataFrame, List[Any]], schema: Optional[Any] = None) -> DataFrame: ...
    def stop(self) -> None: ...
    
    class Builder:
        def master(self, master: str) -> 'SparkSession.Builder': ...
        def appName(self, name: str) -> 'SparkSession.Builder': ...
        def config(self, key: str, value: Any) -> 'SparkSession.Builder': ...
        def getOrCreate(self) -> 'SparkSession': ...

class Row:
    def asDict(self, recursive: bool = ...) -> Dict[str, Any]: ... 