from typing import Any, Optional, Union, List, TypeVar, ClassVar
import pandas as pd

T = TypeVar("T")

class SparkSession:
    class Builder:
        builder: ClassVar["SparkSession.Builder"]

        def master(self, master: str) -> "SparkSession.Builder": ...
        def appName(self, name: str) -> "SparkSession.Builder": ...
        def config(self, key: str, value: Any) -> "SparkSession.Builder": ...
        def getOrCreate(self) -> "SparkSession": ...

    builder: ClassVar[Builder]
    def createDataFrame(
        self, data: Union[pd.DataFrame, List[Any]], schema: Optional[List[str]] = None
    ) -> "DataFrame": ...
    def stop(self) -> None: ...

class DataFrame:
    def __init__(self) -> None: ...
    def count(self) -> int: ...
    def drop(self, *cols: str) -> "DataFrame": ...
    def select(self, *cols: str) -> "DataFrame": ...
    def toPandas(self) -> pd.DataFrame: ...
    @property
    def columns(self) -> List[str]: ...
